In [33]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns 

## 🎲 Generate a Random Matrix:

In [34]:
import numpy as np


def generate_matrix(rows: int, columns: int, distributions: list[tuple[float, float]] = None, global_mean_std: tuple[float, float] = None) -> np.ndarray:
    """
    Generates a matrix where each column follows a specified normal distribution.
    
    Parameters:
    rows (int): Number of rows in the matrix.
    columns (int): Number of columns in the matrix.
    distributions (list of tuples, optional): A list where each tuple contains (mean, std) for the normal distribution
                                              of the corresponding column. The length must match the number of columns.
    global_mean_std (tuple, optional): A single (mean, std) pair to be applied to all columns if distributions are not provided.
    
    Returns:
    np.ndarray: Generated matrix with specified distributions.
    """
    if global_mean_std:
        mean, std = global_mean_std
        return np.random.normal(loc=mean, scale=std, size=(rows, columns))

    if distributions is None or len(distributions) != columns:
        raise ValueError(
            "Number of distributions must match the number of columns or provide a global mean and std.")

    matrix = np.zeros((rows, columns))
    for col in range(columns):
        mean, std = distributions[col]
        matrix[:, col] = np.random.normal(loc=mean, scale=std, size=rows)

    return matrix


### 📌 Example:

In [35]:
# Example usage:
rows = 5
columns = 3
# Mean and std deviation for each column
specific_distributions = [(0, 1), (5, 2), (-3, 0.5)]
global_distribution = (2, 1)  # Apply same mean and std to all columns

# Using specific distributions

matrix1 = generate_matrix(rows, columns, distributions=specific_distributions)
print("Matrix with specific distributions:\n", matrix1)

# Using global mean and std
matrix2 = generate_matrix(rows, columns, global_mean_std=global_distribution)
print("\nMatrix with global distribution:\n", matrix2)

Matrix with specific distributions:
 [[ 1.45800423  2.53104561 -2.54283828]
 [ 0.41672952  5.95905397 -3.93393767]
 [ 1.09977401  6.88361991 -3.88536024]
 [-0.19600599  3.26607686 -3.01189665]
 [-1.60409548 10.43963202 -2.2142676 ]]

Matrix with global distribution:
 [[ 0.12891741 -0.07194887  2.20138157]
 [ 0.93980367  1.93525332  1.4446796 ]
 [ 1.95272371  1.9116349   2.49124925]
 [ 2.05482924  2.26234888  2.56004163]
 [ 1.42011853  1.69625071  1.80003546]]


In [ ]:
from typing import List, Tuple, Dict, Union


def generate_matrices(num_matrices: int, rows: int, columns: int, storage_type: str = "array",
                      distributions: List[Tuple[float, float]] = None, global_mean_std: Tuple[float, float] = None) -> Union[List[np.ndarray], Dict[str, np.ndarray]]:
    """
    Generates multiple matrices and stores them in either a list (array) or a dictionary.
    
    Parameters:
    num_matrices (int): Number of matrices to generate.
    rows (int): Number of rows per matrix.
    columns (int): Number of columns per matrix.
    storage_type (str): Either "array" for a list or "dict" for a dictionary.
    distributions (List[Tuple[float, float]], optional): List of (mean, std) pairs for each column.
    global_mean_std (Tuple[float, float], optional): Single (mean, std) pair for all columns.
    
    Returns:
    Union[List[np.ndarray], Dict[str, np.ndarray]]: Generated matrices stored as a list or dictionary.
    """
    if storage_type not in ["array", "dict"]:
        raise ValueError("storage_type must be either 'array' or 'dict'")

    if storage_type == "array":
        return [generate_matrix(rows, columns, distributions, global_mean_std) for _ in range(num_matrices)]
    else:
        return {f"matrix_{i}": generate_matrix(rows, columns, distributions, global_mean_std) for i in range(num_matrices)}

NameError: name 'List' is not defined

In [ ]:
# Example usage:
num_matrices = 3
rows = 5
columns = 3
# Mean and std deviation for each column
specific_distributions = [(0, 1), (5, 2), (-3, 0.5)]
global_distribution = (2, 1)  # Apply same mean and std to all columns

# Generate list of matrices
matrix_list = generate_matrices(
    num_matrices, rows, columns, "array", specific_distributions)
print("List of Matrices:", matrix_list)

# Generate dictionary of matrices
matrix_dict = generate_matrices(
    num_matrices, rows, columns, "dict", global_mean_std=global_distribution)
print("\nDictionary of Matrices:", matrix_dict)

ValueError: storage_type be either 'array' or 'dict'

## Discernibility Analysis:

In [ ]:
def Discernibility_Analysis(mat1, mat2):

    return np.mean(mat1-mat2<0)